language: c

sudo: false

compiler:
- gcc
- clang

env:
  global:
  - CFLAGS='-Werror'
  - DISTCHECK_CONFIGURE_FLAGS='${CONFIGURE_ARGS}'
  matrix:
  - CONFIGURE_ARGS='--enable-debug --with-crypto-lib=libgcrypt'
  - CONFIGURE_ARGS='--enable-debug --with-crypto-lib=openssl'
  - CONFIGURE_ARGS='--disable-debug --with-crypto-lib=libgcrypt'
  - CONFIGURE_ARGS='--disable-debug --with-crypto-lib=openssl'

addons:
  apt:
    packages:
    - zlib1g-dev
    - libbz2-dev
    - libgcrypt11-dev
    - libssl-dev
    - colormake

script:
- ./configure ${CONFIGURE_ARGS} && colormake -e -k && colormake -e distcheck
