language: c

sudo: false

compiler:
- gcc
- clang

env:
  global:
  # Encrypted COVERITY_SCAN_TOKEN
  - secure: "BQDASY4yNtsHV5bX6CDcFux4csQ4lkKm+Ihjwslab6XVOX8YAQrFeq6bHw+eCl8uCybrwUCOHYavvCHAFIBp5ik5D/NZUid+U1Yk1DSw6NcXpLMhEZDx9GVupyjExwFCOHMGnIRXcOI1mEMMaPHQQZWKixTVZX9350Dku6Qu3AXFjTSf3aCQLoazxGoNQveefmaqLLOg/kUgfGQV2eW8J4b9UKw3mdaDa651jdLaAOvKunRlI22j675JkFE45f0+RG/DtqSEfoDc3eAnsSebl9bj9JPNS4qgXschM0WaDUoogJFKcZ+OeLRPGQDGZUvCmvBE7mprOiFYtkFihAZmVpZ7pT1kgtmEnyuRX0+yaJN/YW+EQ5Nht89c5pM5BxInDXlyQWW1Kn9qXacpdIA8YTKswxa58tWQJp7c6oqaCrN5dUV3QvRJFLMxCMI3Ptjl196G4lZvVlT5ZyoYYnIhDmwoTrI1rhjKpnOQG9Ce64Jdlaf6c+5GPXHoqDSc8/zRWTVZrJJWnFStTSakLNDmdZtVO2bj5EQnMRgcaxK9uwmxRAUJvcocq1KKvkByesLD/5bH3d+gM9LL0NcJKjPRqgPL2amjXXqBuGRo9MSiEicgFPZ6inV/MUZGdTO4Lzr/8X5gqUl3cuvjybTDlu4izBSn3iCt5yZCQb2mtTx7m18="
  - CFLAGS='-Werror'
  - DISTCHECK_CONFIGURE_FLAGS='${CONFIGURE_ARGS}'
  matrix:
  - CONFIGURE_ARGS='--enable-debug --with-crypto-lib=libgcrypt'
  - CONFIGURE_ARGS='--enable-debug --with-crypto-lib=openssl'
  - CONFIGURE_ARGS='--disable-debug --with-crypto-lib=libgcrypt'
  - CONFIGURE_ARGS='--disable-debug --with-crypto-lib=openssl'

addons:
  apt:
    packages:
    - zlib1g-dev
    - libbz2-dev
    - libgcrypt11-dev
    - libssl-dev
    - colormake
  coverity_scan:
    project:
      name: "dun/munge"
      description: "MUNGE Uid 'N' Gid Emporium"
    notification_email: cdunlap@llnl.gov
    build_command_prepend: "./configure"
    build_command:   "make"
    branch_pattern: coverity_scan

script:
- if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ./configure ${CONFIGURE_ARGS} && colormake -e -k && colormake -e distcheck; fi
